[workspace]
members = [
    "crates/modkit-tools",
    "crates/stellar-blade-bouldy-mod",
]
exclude = ["vendor/bouldy"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "ssh://git@github.com/caniko/rs-stellar-blade-mod-kit.git"
rust-version = "1.80"

[workspace.lints.rust]
unsafe_op_in_unsafe_fn = "deny"
missing_docs = "warn"

[workspace.lints.clippy]
undocumented_unsafe_blocks = "deny"

[workspace.metadata.crane]
name = "stellar-blade-bouldy-mod"
